# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4UkWJ9ZeD3kp1xJllheHRC6AVFEB7PU
"""

import numpy as np
import matplotlib.pyplot as plt

N = 500
phi = 0.3
v0 = 1.0
Dr = 0.1
dt = 0.1
total_steps = 10000
L = np.sqrt(N * np.pi * 0.5**2 / phi)

x = np.random.uniform(0, L, N)
y = np.random.uniform(0, L, N)
angles = np.random.uniform(0, 2*np.pi, N)

x_raw = x.copy()
y_raw = y.copy()
x0 = x.copy()
y0 = y.copy()

msd_list = []
time_axis = []

for i in range(total_steps):
    angles += np.random.normal(0, 1, N) * np.sqrt(2 * Dr * dt)

    # move particles
    dx = v0 * np.cos(angles) * dt
    dy = v0 * np.sin(angles) * dt

    x += dx
    y += dy
    x_raw += dx
    y_raw += dy

    x = x % L
    y = y % L

    if i % 10 == 0:
        dist_sq = (x_raw - x0)**2 + (y_raw - y0)**2
        msd_list.append(np.mean(dist_sq))
        time_axis.append(i * dt)

plt.figure(figsize=(8,6))
plt.plot(time_axis, msd_list, label='sim data')

t_arr = np.array(time_axis)
plt.plot(t_arr, (v0**2)*(t_arr**2), 'k--', label='t^2')
plt.plot(t_arr, (2*v0**2/Dr)*t_arr, 'r--', label='t')

plt.xscale('log')
plt.yscale('log')
plt.xlabel('Time')
plt.ylabel('MSD')
plt.legend()
plt.title('MSD log-log')
plt.show()

s1 = (np.log(msd_list[5]) - np.log(msd_list[1])) / (np.log(time_axis[5]) - np.log(time_axis[1]))
s2 = (np.log(msd_list[-1]) - np.log(msd_list[-10])) / (np.log(time_axis[-1]) - np.log(time_axis[-10]))
print("Short time slope:", s1)
print("Long time slope:", s2)